//
//  ShowCityRouter.swift
//  Weather
//
//  Created by Javier Jara on 11/16/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowCityRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowCityDataPassing
{
  var dataStore: ShowCityDataStore? { get }
}

class ShowCityRouter: NSObject, ShowCityRoutingLogic, ShowCityDataPassing
{
  weak var viewController: ShowCityViewController?
  var dataStore: ShowCityDataStore?

}
