//
//  ShowCityViewController.swift
//  Weather
//
//  Created by Javier Jara on 11/16/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowCityDisplayLogic: class{
    func displayCity(viewModel: ShowCity.GetCity.ViewModel)
}

class ShowCityViewController: UIViewController, ShowCityDisplayLogic {
    var interactor: ShowCityBusinessLogic?
    var router: (NSObjectProtocol & ShowCityRoutingLogic & ShowCityDataPassing)?
    // MARK: Object lifecycle
    
    @IBOutlet weak var windSpeedLabel: UILabel!
    @IBOutlet weak var atmLabel: UILabel!
    @IBOutlet weak var humidityLabel: UILabel!
    @IBOutlet weak var tempMaxLabel: UILabel!
    @IBOutlet weak var tempMinLabel: UILabel!
    @IBOutlet weak var tempLabel: UILabel!
    @IBOutlet weak var weatherImage: UIImageView!
    @IBOutlet weak var tempMedLabel: UILabel!
    @IBOutlet weak var weatherDescLabel: UILabel!
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = ShowCityInteractor()
        let presenter = ShowCityPresenter()
        let router = ShowCityRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)

        fetchCityWeather()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetchCityWeather(){
        let request = ShowCity.GetCity.Request()
        interactor?.getCity(request: request)
    }
    
    func displayCity(viewModel: ShowCity.GetCity.ViewModel) {
        self.title = viewModel.displayedCity.name
        windSpeedLabel.text = viewModel.displayedCity.windSpeed
        atmLabel.text = viewModel.displayedCity.atm
        humidityLabel.text = viewModel.displayedCity.humidity
        tempMaxLabel.text = viewModel.displayedCity.tempMax
        tempMinLabel.text = viewModel.displayedCity.tempMin
        tempLabel.text = viewModel.displayedCity.temp
        tempMedLabel.text = viewModel.displayedCity.temp
        weatherImage.image = UIImage(named: viewModel.displayedCity.imageName)
        weatherDescLabel.text = viewModel.displayedCity.weatherDescription
    }
}
