//
//  ShowCityInteractor.swift
//  Weather
//
//  Created by Javier Jara on 11/16/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowCityBusinessLogic {
    func getCity(request: ShowCity.GetCity.Request)
}

protocol ShowCityDataStore {
    var city: City! {get set}
}

class ShowCityInteractor: ShowCityBusinessLogic, ShowCityDataStore {
    var presenter: ShowCityPresentationLogic?
    var worker: ShowCityWorker?
    var city: City!
    
    func getCity(request: ShowCity.GetCity.Request) {
        let response = ShowCity.GetCity.Response(city: city)
        presenter?.presentCity(response: response)
    }
}
