//
//  ListCitiesPresenter.swift
//  Weather
//
//  Created by Javier Jara on 11/15/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListCitiesPresentationLogic {
    func presentCities(response: ListCities.FetchCities.Response)
    func presentError(response: Error)
}

class ListCitiesPresenter: ListCitiesPresentationLogic
{
    weak var viewController: ListCitiesDisplayLogic?
    
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none
        return dateFormatter
    }()
    
    func presentCities(response: ListCities.FetchCities.Response) {
        
        let citiesViewModel = response.cities.map{ListCities.FetchCities.ViewModel.DisplayedCity(cityId: $0.cityId, name: $0.name, temperature: $0.main.temp)}
        let dateNow = dateFormatter.string(from: Date())
        let viewModel = ListCities.FetchCities.ViewModel(displayedCities: citiesViewModel, lastUpdate:dateNow)
        viewController?.displayCities(viewModel: viewModel)
    }
    
    func presentError(response: Error) {
        
    }
    
//  func presentSomething(response: ListCities.FetchCities.Response)
//  {
//    let viewModel = ListCities.FetchCities.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
