//
//  ListCitiesInteractor.swift
//  Weather
//
//  Created by Javier Jara on 11/14/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListCitiesInteractorInteractorInput
{
  func doSomething(request: ListCitiesInteractor.Something.Request)
}

protocol ListCitiesInteractorInteractorOutput
{
  func presentSomething(response: ListCitiesInteractor.Something.Response)
}

class ListCitiesInteractorInteractor: ListCitiesInteractorInteractorInput
{
  var output: ListCitiesInteractorInteractorOutput!
  var worker: ListCitiesInteractorWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ListCitiesInteractor.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ListCitiesInteractorWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ListCitiesInteractor.Something.Response()
    output.presentSomething(response: response)
  }
}
