//
//  ListCitiesViewController.swift
//  Weather
//
//  Created by Javier Jara on 11/14/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListCitiesViewControllerViewControllerInput
{
  func displaySomething(viewModel: ListCitiesViewController.Something.ViewModel)
}

protocol ListCitiesViewControllerViewControllerOutput
{
  func doSomething(request: ListCitiesViewController.Something.Request)
}

class ListCitiesViewControllerViewController: UITableViewController, ListCitiesViewControllerViewControllerInput
{
  var output: ListCitiesViewControllerViewControllerOutput!
  var router: ListCitiesViewControllerRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ListCitiesViewControllerConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: - Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ListCitiesViewController.Something.Request()
    output.doSomething(request: request)
  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: ListCitiesViewController.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
