//
//  ListCitiesRouter.swift
//  Weather
//
//  Created by Javier Jara on 11/15/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListCitiesRoutingLogic {
    func routeToShowCity(segue: UIStoryboardSegue?)
}

protocol ListCitiesDataPassing {
  var dataStore: ListCitiesDataStore? { get }
}

class ListCitiesRouter: NSObject, ListCitiesRoutingLogic, ListCitiesDataPassing {
  
    weak var viewController: ListCitiesViewController?
    var dataStore: ListCitiesDataStore?
  
  // MARK: Routing
  
    
    func routeToShowCity(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ShowCityViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowCity(source: dataStore!, destination: &destinationDS)
        } else {
            let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "ShowCityViewController") as! ShowCityViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToShowCity(source: dataStore!, destination: &destinationDS)
            navigateToShowCity(source: viewController!, destination: destinationVC)
        }
    }
    
  // MARK: Navigation
  
  func navigateToShowCity(source: ListCitiesViewController, destination: ShowCityViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
    
    func passDataToShowCity(source: ListCitiesDataStore, destination: inout ShowCityDataStore) {
//        destination.name = source.name
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        let city = source.cities?[selectedRow!]
        destination.city = city
    }
}
