//
//  ListCitiesModels.swift
//  Weather
//
//  Created by Javier Jara on 11/15/17.
//  Copyright (c) 2017 jjsoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListCities {
  // MARK: Use cases
  
  enum FetchCities {
    struct Request{
        
    }
    struct Response{
        var cities: [City]
    }
    
    struct ViewModel {
        struct DisplayedCity {
            var cityId: String
            var name: String
            var temperature: String
            var weatherImageName: String
        }
        var displayedCities: [DisplayedCity]
        var lastUpdate: String
    }
  }
}

struct City {
    var cityId: String
    var name: String
    var main: Main
    var weather: Weather?
    var wind: Wind
    
    init(dictionary: [String: Any]){
        self.cityId = String(describing: dictionary["id"] as? Int ?? 0)
        self.name = dictionary["name"] as? String ?? ""
        self.main = Main(dictionary: dictionary["main"] as? [String: Any] ?? [:])
        self.wind =    Wind(dictionary: dictionary["wind"] as? [String: Any] ?? [:])
        let dict = dictionary["weather"] as? [Any]
        if let weatherDict = (dict?.first as? [String: Any]) {
                self.weather = Weather(dictionary: weatherDict)
        }
        
    }
}

struct Main{
    var temp: String
    var humdity: String
    
    init(dictionary: [String: Any]){
        self.temp = String(describing: dictionary["temp"] as? Float ?? 0)
        self.humdity = String(describing: dictionary["humidity"] as? Int ?? 0)

    }
}

struct Weather {
    var weatherDescription: String
    var code: Int
    
    init(dictionary: [String: Any]){
        self.weatherDescription = dictionary["description"] as? String ?? ""
        self.code = dictionary["id"] as? Int ?? 0
    }
}

struct Wind {
    var speed: String
    
    init(dictionary: [String : Any]){
        self.speed = String(describing: dictionary["speed"] as? Int ?? 0)
    }
}
